- search/live-filter/index.js
- search/live-filter/live-filter-facet.js
Facet title are now translated. The base path is `live.filter.facets.FACET_NAME`
> Fix non opening facets. Add i18n

- .travis.yml
Avoid react warning, and enable animations
> Add keys to live filter component

- page/search/advanced-search/index.js
> [advanced-search] Add componentWillReceiveProps

- common/button/back-to-top/index.js
- common/detail/index.js
- common/mixin/scroll-to.js
- common/sticky-navigation/example/index.html
- common/sticky-navigation/index.js
- common/sticky-navigation/style/sticky-navigation.scss
Closes KleeGroup/focus-demo#35
> Sticky navigation

- page/search/advanced-search/index.js
- page/search/common/group-by-mixin.js
Resolves Kleegroup/focus-demo#43
> [advanced-search] No decoration if single group

- common/sticky-navigation/index.js
Resolves Kleegroup/focus-demo#95
> [sticky-navigation] Change first element detection range to start at 0

- search/search-bar/index.js
Resolves Kleegroup/focus-demo#93
> [search-bar] Focus on mount

- common/input/checkbox/index.js
Fix https://github.com/KleeGroup/focus-demo/issues/72
> [checkbox] material checkbox Fix #72

- common/select-action/index.js
- list/action-bar/index.js
- list/action-contextual/index.js
- page/search/advanced-search/index.js
- page/search/common/search-mixin.js
Resolves Kleegroup/focus-demo#58
Resolves Kleegroup/focus-demo#75
Resolves Kleegroup/focus-demo#76
Resolves Kleegroup/focus-demo#77
> Advanced search fix

- page/search/common/group-by-mixin.js
Resolves Kleegroup/focus-demo#81
> [search] Add message if no result

- common/button/back-to-top/index.js
- common/button/back-to-top/style/back-to-top.scss
- common/detail/index.js
- common/sticky-navigation/index.js
- page/search/advanced-search/index.js
Fix https://github.com/KleeGroup/focus-demo/issues/50
> Back to top

- search/facet-box/facet.js
Resolves Kleegroup/focus-demo#78
> [facets] Show all now working

- common/form/mixin/reference-behaviour.js
- page/search/index.js
- page/search/search-header/action-wrapper.js
- page/search/search-header/cartridge.js
- page/search/search-header/index.js
- page/search/search-header/mixin/index.js
- page/search/search-header/summary.js
- search/search-bar/index.js
Fix https://github.com/KleeGroup/focus-demo/issues/73
Fix https://github.com/KleeGroup/focus-demo/issues/74
> Search header

- common/sticky-navigation/index.js
- common/sticky-navigation/style/sticky-navigation.scss
Resolves Kleegroup/focus-demo#106
> [sticky-navigation] Remove bootstrap behaviour, make our own for affix

- common/mixin/store-change-behaviour.js
- page/search/common/search-mixin.js
- page/search/quick-search/index.js
- page/search/search-header/action-wrapper.js
- page/search/search-header/mixin/index.js
- search/index.js
- search/mixin/index.js
- search/mixin/query-store-behaviour.js
- search/search-bar/index.js
> Query store

- application/error-center/index.js
- application/error-center/style/error-center.scss
- application/layout/index.js
Fix https://github.com/KleeGroup/focus-demo/issues/163
> Error center

- page/search/advanced-search/index.js
Resolves Kleegroup/focus-demo#157
> [advanced-search] Fix ungroup

- common/field/mixin/built-in-components.js
> [select] Resolve value to label in consult mode

- common/form/index.js
- package.json
- page/detail/example/index.html
- page/detail/example/wizard.html
- Update the form to be able to update for outside its `isEdit` property in the state
- Add a wizard example with super simple conf and use (maybe this will be soon converted into a real page component)
//```javascript
{
componentName: {
component: ReferenceToYourComponent,
steps:{
//X is the step number
X: {
isVisible: true | false // Is your node visible in the step.
props: {isEdit: true} // this is an example. You just specify the props you want for your component in the given step.
}
}
},
otherComponentName: {
component: Ref,//...
steps:{} //... Same thing.
}
}
```
```jsx
<Wizard configuration={myConf} />
```
> Wizard example

- src/list/selection/example/index.html
- src/list/selection/list.js
Add the ability to specify the selection status line by line in a list.
> Selections

- src/application/menu/index.js
- src/common/autocomplete/awesomplete.js
- src/common/autocomplete/field.js
- src/page/search/advanced-search/index.js
- src/page/search/quick-search/index.js
Fix the remaning React warnings.
> Fix warnings

- src/common/field/mixin/validation-behaviour.js
- src/common/form/example/index.html
- src/common/form/index.js
- src/common/form/mixin/index.js
- src/common/form/mixin/validation-behaviour.js
> Custom validation

- src/application/menu/index.js
> [menu] Fix #194 button type

- src/common/label/index.js
- src/list/summary/example/index.html
- src/list/summary/index.js
> Fix export summary

- src/common/select/classic/example/index.html
- src/common/select/classic/index.js
- src/mixin/stylable.js
Fix https://github.com/KleeGroup/focus-components/issues/183
Fix  https://github.com/KleeGroup/focus-components/issues/186
> Select fix

- src/common/mixin/field-component-behaviour.js
Fix https://github.com/KleeGroup/focus-components/issues/206
> [field-props] Add field props and es6 style.

- .gitignore
- example/index.html
- package.json
- scripts/load-dependencies.js
- scripts/script-loader.js
- scripts/style-loader.js
- src/common/form/example/index.html
Script loading...
```html
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Focus component examples</title>
<meta name="description" content="Example of the component.">
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="/focus-components/example/js/browser.js"></script>
<script src="/focus-components/example/js/assets.js"></script>
</head>
<body>
<div id="example-component-container"></div>
<script type='text/babel'>
loadAssets().then(function(d){
//Execute my super component example code.
});
</script>
```
In order to build the example perform once
`npm install` and `npm run build:example`
> Script loader

- package.json
- scripts/style-loader.js
- src/common/sticky-navigation/example/index.html
> Sticky nav sample

- package.json
- src/application/error-center/example/index.html
- src/application/error-center/index.js
- src/application/index.js
> [error] improve error component add react errors.

- src/application/popin/index.js
> [popin] Fix bad scroll bar behaviour

- src/common/form/example/index.html
- src/common/form/style/form.scss
> Form example fix

- src/common/block/index.js
- src/common/scrollspy/example/index.html
- src/common/scrollspy/index.js
- src/common/title/example/index.html
- src/common/title/index.js
> Scrollspy corrections

- .gitignore
- package.json
- scripts/components-scanner.js
- src/application/catalog/example/index.js
- src/application/catalog/package.json
Add a component catalog build:
Each component should have a private `package.json` file with the following properties: 
`'name','version','description','keywords','photo','homepage'`
Also a directory with a `example/index.js` file which will be copied as `code` property.
The generated code will be as follows: 
```json
[
{
"name": "catalog",
"version": "1.0.0",
"description": "catalog component",
"keywords": [
"catalog",
"focus-components"
],
"code": "module.exports = function(){\r\n    console.log('EXAMPLE.......');\r\n}\r\n"
}
]
```
Add npm scripts  `npm run showcase` to launch:
- components-build :+1: 
- asset build
- dependency copy from npm `babel/browser.js` :+1:
> Feature component parser

- src/application/popin/index.js
> [popin] Fix error on closing

- src/common/form/mixin/validation-behaviour.js
> [validator] Fix missing return on deprecated validate. 

- src/common/field/mixin/built-in-components.js
- src/showcase/catalog/components.json
Fix #236
Fixes on eslint, and let replace by const, are missing because it's already done on feature-material branch.
> [field] select read values in the props and not in the state. 

- src/common/display/text/index.js
Fix https://github.com/KleeGroup/focus-components/issues/240
> [display] Rewrite component and pass all props to the children.

- package.json
- src/list/action-contextual/index.js
- src/list/selection/README.md
- src/list/selection/line.js
- src/list/selection/list.js
> [list] Customizable buttons, props passed everywhere

- src/search/search-bar/index.js
> Customize search placeholder

- src/common/input/checkbox/index.js
- src/common/input/index.js
- src/common/input/radio/example/index.js
- src/common/input/radio/index.js
- src/common/input/radio/package.json
- src/common/input/radio/style/radio.scss
- src/common/select/radio/example/index.js
- src/common/select/radio/index.js
- src/common/select/radio/package.json
- src/common/select/radio/style/select-radio.scss
> [select-radio] refactor component for MDL

- src/common/input/textarea/example/index.js
- src/common/input/textarea/index.js
- src/common/input/textarea/package.json
> [input textarea] Feature material textarea + add to catalogue

- src/list/selection/example/index.html
- src/list/selection/list.js
> [list] Fix bad data given to lines

- src/common/button/action/example/index.js
- src/common/button/action/index.js
- src/common/button/action/package.json
> [material][button] feature.

- src/common/block/example/index.js
- src/common/block/index.js
- src/common/block/style/block.scss
> Feature material block

- src/common/select/checkbox/example/index.js
- src/common/select/checkbox/package.json
> [select-checbox] refactor for mdl and add to catalog

- src/common/field/index.js
- src/common/form/example/index.js
- src/common/form/package.json
> Feature material form

- src/common/button/action/index.js
- src/common/button/action/style/button.scss
- src/common/mixin/built-in-components.js
> [button-action] improvement : add font-awesome support

- src/common/icon/example/index.js
- src/common/icon/index.js
- src/common/icon/package.json
> [icon] Add icon material and font awesome

- src/common/column/example/index.js
- src/common/column/index.js
- src/common/column/package.json
- src/common/grid/index.js
- src/common/index.js
> Feature material column

- src/common/progress-bar/index.js
- src/common/progress-bar/style/progress-bar.scss
> [progress-bar] Fix style

- src/message/example/index.js
- src/message/index.js
- src/message/package.json
- src/message/style/message.scss
> [mdl] Rewrite message add material style.

- src/application/layout/style/layout.scss
- src/common/button/back/index.js
> Feature material back button

- src/application/header/index.js
- src/application/loading-bar/index.js
- src/application/loading-bar/style/loading-bar.scss
> Fix header + dev bar

- src/common/button/back-to-top/index.js
- src/common/button/back-to-top/style/back-to-top.scss
> [button top] Material style

- src/common/block/style/block.scss
- src/common/select/checkbox/example/index.js
- src/common/select/checkbox/index.js
- src/common/select/radio/index.js
- The component when in unontrolled mode does node update the component local state
- Fix `getValues` is now `getValues`
> Hotfix checkbox onchange

- src/common/field/mixin/built-in-components.js
- src/common/field/style/field.scss
- src/common/form/example/index.js
- src/common/mixin/field-component-behaviour.js
- src/common/select/radio/index.js
- src/style/_mdl_variables.scss
**Add possibilty to declare possible value directly in the domain (Domain YES/NO)**
To declare the the value in domain
```javascript
'DO_OUI_NON': {
InputComponent: FocusComponents.common.select.radio.component,
refContainer: {ouiNonList: [{code: true, label: "select.oui"}, {code: false, label: "select.non"}]},
listName: 'ouiNonList'
}
```
**correction of checkbox field style**
**Correction of checkbox : delegate state management to parent when onchange method is overrided.**
fix #314
fix #335
> Hotfix 314 - 335 checkbox and radio fix

- .gitignore
See https://coveralls.io/github/KleeGroup/focus-components
> Add coveralls support

- src/list/action-contextual/index.js
> [action-contextual] Fix icon given to the button

- src/common/input/date/index.js
> [date] Add the possibility to set a null value

- src/application/menu/index.js
> [menu] Whole link is now clickable

- src/common/scrollspy/style/scrollspy.scss
Scrollspy
Remove padding css to correct display issue.
fix #351
> [scrollspy] remove padding css. fix #351.

- src/common/display/text/index.js
- src/common/form/example/index.js
display text now translate value
fix #339
> [display-text] display text now translate value

- src/common/input/text/index.js
Translate the placeholder in the input component. 
Fix #322
> [input]  translate placeholder

- src/common/field/example/index.js
- src/common/select/classic/example/index.js
- src/common/select/classic/index.js
- src/common/select/classic/package.json
[select-classic] add disabled property.
fix #280
> [select-classic] add disabled property. fix #280

- .travis.yml
- package.json
- Add develop branch publish by travis
- rename `package` name into `focus-components`
> Feature npm publish

- src/common/input/date/example/index.js
- src/common/input/date/index.js
[input-date] Correct the display of date in the input at initialazation of component.
fix #386.
> [input-date] correct display of input with null value date. fix #386.

- package.json
Add lib/ for webpack compliance
> Change main property #394

- src/common/mixin/field-component-behaviour.js
> [form] Apply @duranx fix

- scripts/load-dependencies.js
- src/common/autocomplete/awesomplete.js
- src/common/autocomplete/example/index.js
- src/common/autocomplete/field.js
- src/common/autocomplete/package.json
- src/common/field/index.js
- src/common/field/mixin/built-in-components.js
- src/common/form/example/index.js
- src/common/mixin/built-in-components.js
> Hotfix 288 autocomplete selection handler

- package.json
- scripts/load-dependencies.js
- src/common/autocomplete/awesomplete.js
- src/common/autocomplete/example/index.js
- src/common/autocomplete/field.js
- src/common/autocomplete/package.json
- src/common/field/index.js
- src/common/field/mixin/built-in-components.js
- src/common/form/example/index.js
- src/common/input/date/example/index.js
- src/common/input/date/index.js
- src/common/mixin/built-in-components.js
- src/common/mixin/field-component-behaviour.js
> Hotfix v0.6.1-6

- src/common/form/index.js
Fix the html5 validation problem which was triggered when an error occurs.
> [form] Fix intrusive html5 validation.

- src/common/field/index.js
- src/common/field/mixin/built-in-components.js
- src/common/field/style/field.scss
- src/common/form/example/index.js
- src/common/form/index.js
- src/common/input/date/index.js
- src/common/input/text/index.js
- src/common/input/textarea/index.js
- src/common/mixin/field-component-behaviour.js
- src/common/select/classic/index.js
- src/common/select/classic/style/select.scss
Get all 0.6.2 bugs into develop
> Cherry pick 0.6.2

- src/common/select/classic/index.js
> [select] Fix the Nan Value of the unselected key.

- src/common/mixin/built-in-components.js
> [button delete] Add this context to the button.

- src/common/form/example/index.js
- src/common/input/radio/style/radio.scss
- src/style/index.js
Correction of declaration of sass files.
> [CSS] correction of sass file declaration

- package.json
- src/common/autocomplete/awesomplete.js
- src/common/autocomplete/field.js
> Fix autocomplete component

- src/components/scrollspy-container/index.js
now debounce position calculation on scroll
> [scrollspy] now debounce position calculation on scroll

- app.json
- src/showcase/focus-showcase.webpack.js
> Fix deploy to Heroku

- .travis.yml
> [travis] Enable cache

- src/components/scrollspy-container/index.js
* correction of null refs
fix #501
> [ScrollspyContainer] correction of null refs

- src/search/search-bar/scope.js
Scope bar is now display when a second search bar is in the DOM.
> [search-bar] add unique scope id. fix.

- src/search/search-bar/style/search-bar.scss
> [search-bar] correction of styles

- src/application/popin/style/popin.scss
- src/components/layout/style/header-scrolling.scss
- src/components/layout/style/header-top-row.scss
- src/search/search-bar/style/search-bar.scss
> [layout] add flex css in top header

- src/components/panel/style/panel.scss
Correct panel content width.
Fix #542
> [panel] correct content width

- src/common/form/example/index.js
- src/common/mixin/field-component-behaviour.js
Fix select rendering when no values.
Fix #376
> [field] correct select component values (when no values). 

- package.json
- src/components/input/index.js
- src/components/input/text/index.js
- src/components/input/textarea/example/index.js
- src/components/input/textarea/index.js
- src/components/input/textarea/package.json
- src/components/input/textarea/style/textarea.scss
- src/style/_mdl_variables.scss
- src/style/index.js
* component rewritten to run without state
* component now display errors
> Feature textarea : correction 

- src/behaviours/index.js
- src/index.js
Add them to the namespace
```
.
├── translation
├── componentBase
├── scroll
├── connect
└── material
```
> [namespace] Add behaviours

- src/common/button/action/index.js
- src/common/icon/index.js
You can now add a custom font for your icons in buttons and icons.
On button you just have to add the props ` iconLibrary='font-custom' `
```jsx
<Button icon='mood'  iconLibrary='font-custom' label='minifabbutton' color='announcement' shape='mini-fab' type='button' handleOnClick={()=> alert('click bouton')}/>
```
On button you just have to add the props ` iconLibrary='font-custom' `
```jsx
<Icon name='circle' library='font-custom'/>
```
You can use [icomoon](https://icomoon.io/app/) in order to generate your custom font from your svg icons.
You can upload your icons 
And generate an export with a 
You then have sevral fonts files in the font directory 
Fix #552, #384
> Feature custom font

- src/list/action-bar/index.js
Don't pay attention to the branch name, the issue was already fixed.
> [advanced search] Change folder icon

- src/common/autocomplete/awesomplete.js
When the user types fast in the input field, the selection list is not displayed.
The selection list is now displayed reliably.
> Fix #537 autocomplete race typing

- src/application/popin/index.js
- src/common/button/action/index.js
- src/common/column/index.js
- src/common/field/mixin/built-in-components.js
- src/common/grid/index.js
- src/common/icon/index.js
- src/common/mixin/field-grid-behaviour.js
- src/common/select/classic/index.js
- src/components/layout/header-scrolling.js
- src/components/layout/index.js
Fix react warnings due to props 
Fix #503
> Fix react warnings

- package.json
> [version] 0.7.3

- package.json
- src/components/index.js
- src/components/layout/header-default-template.js
- src/components/layout/header-scrolling.js
- src/components/layout/index.js
Add the ability to override default header.
> Fetaure publish layout private

- package.json
- src/common/list/index.js
- src/common/mixin/built-in-components.js
- src/common/select-action/index.js
- src/components/input/checkbox/example/index.jsx
- src/components/input/checkbox/index.js
- src/list/selection/list.js
- src/list/timeline/list.js
- src/page/search/advanced-search/index.js
- src/search/search-bar/scope.js
> Hotfix 0.7.3-1

- package.json
- src/list/selection/list.js
- src/list/timeline/list.js
> Hotfix 0.7.3 2

- package.json
- src/common/list/index.js
- src/common/mixin/built-in-components.js
- src/list/table/list.js
Fixes issues with `lineComponent` in lists.
> Hotfix 0.7.3-3

- src/application/error-center/index.js
- src/common/input/date/style/date.scss
- src/common/mixin/built-in-components.js
Forms, dates and error center.
There's more but they were the ones that I noticed the most.
> Switch font-awesome for material for main icons

- src/list/selection/line.js
Lists used to have the wrong Checkbox component, so the fixes on the checkbox did not affect the lists (and by extension the search results).
The checkbox used is now the new one.
> Fix #626 Wrong Checkbox component in lists

- package.json
Please see the changelog here : https://facebook.github.io/react/blog/2015/10/28/react-v0.14.1.html
> [React] Update to version 0.14.1

- src/common/autocomplete/awesomplete.js
- src/list/selection/list.js
Check if `selectionHandler` exists before calling it, as @remigrange suggested.
Fix the `LineComponent` prop type.
> Small fixes

- src/page/search/advanced-search/facet-box.js
See issue #662 
Property added.
Forgot this file on Friday for the pull request because I'm dumb. Thought about it all w-e.
Fixes #662
> [OpenedFacetList] property added to facet-box as well

- src/index.js
> [index] correct imports

- src/application/menu/index.js
> Fix bug iconLibray on Menu Bar

- src/message/index.js
[message mixin] add react import
Add react import in mixin message to work with webpack.
> [message mixin] add react import in mixin message to work with webpack

- package.json
> push version 0.7.5-beta1

- package.json
Update to the new minor version of React, please read the associated [Release note](https://facebook.github.io/react/blog/2015/11/02/react-v0.14.2.html)
> React 0.14.2

- package.json
- src/components/input/date/index.js
Add react import in dependencing to make it work with webpack.
> [input date] add React import

- package.json
- src/style/index.js
> [sass] fix bad css import

- src/common/mixin/built-in-components.js
The cancel button now reset the state from the store before changing the mode.
Fixes #668
> [cancel] The cancel button read the state from the store.

- src/page/list/index.js
Fix a missing Unmount component
> WIP clear list listners when the component is unmounted.

- src/common/mixin/store-behaviour.js
> Fix Server Error display on component Fix #587

- README.md
> [ stats] Update npm stats

- package.json
Update to the new minor version of React, please read the associated [Release note](https://facebook.github.io/react/blog/2015/11/18/react-v0.14.3.html)
> Feature React 0.14.3

- package.json
> feature-0.7.6-rc4

- package.json
- src/components/input/select/index.js
> Fix select nan

- src/common/field/mixin/built-in-components.js
- src/common/input/date/index.js
- src/common/input/text/example/index.html
- src/common/input/text/example/index.js
- src/common/input/text/index.js
- src/components/input/date/index.js
- src/components/input/select/index.js
- src/components/input/text/index.js
- src/components/input/textarea/index.js
Now we use `placeholder` instead of `placeHolder`
> [placeholder] fix misspelling placeHolder => placeholder fix #677

- src/list/selection/line.js
- src/list/selection/list.js
The selection list keeps the selection state even when the provided data change.
The selection state is now reset when data changes
Fixes #699
> Fix selection list keeps the selected state when data changes

- src/components/input/select/index.js
> Cast returned value of select getValue in case of number

- src/components/input/select/__tests__/fixture.js
- src/components/input/select/__tests__/index.js
- src/components/input/select/index.js
> Feature is active list#636

- src/application/popin/index.js
Change the icon to material design.
Fix #711
> [modal] Fix closing icon

- src/page/mixin/cartridge-behaviour.js
It fixes #715 
```javascript
cartridgeConfiguration() {
return {
cartridge: { component: HeaderSearchBar },
};
}
```
> [cartridge] Fix bug

- src/application/confirmation-popin/index.js
- src/application/header/index.js
- src/application/menu/index.js
- src/common/button/action/index.js
- src/common/button/back/index.js
- src/common/column/index.js
- src/common/detail/index.js
- src/common/grid/index.js
- src/common/input/radio/index.js
- src/common/list/index.js
- src/common/select/radio/index.js
- src/components/input/date/index.js
- src/components/layout/header-actions.js
- src/components/menu/index.js
- src/list/selection/line.js
- src/list/selection/list.js
- src/list/summary/index.js
- src/list/timeline/list.js
- src/page/search/advanced-search/index.js
- src/page/search/quick-search/index.js
Fixes a certain amount of warning on `PropTypes`
Fixes #733
> Fix proptypes

- src/common/field/mixin/built-in-components.js
The label is displayed as a placeholder
The placeholder is empty by default.
> [field] Fix placeholdes

- src/components/input/date/index.js
> [date] Add tab handling

- src/common/autocomplete/awesomplete.js
The autocomplete looses the input when the key resolver only is called.
Set a flag when the value is received from the key resolver.
> [autocomplete] Fix blur event

- src/components/input/select/index.js
Check the type of the field to cast the value.
Fixes #746
> [select] Fix casting issues

- src/common/mixin/store-behaviour.js
- src/common/mixin/store-change-behaviour.js
> Fix cancel

- src/list/selection/list.js
First click raises an error.
Fix the error raised.
Fixes #750
> [list] Fix first selection

- src/common/button/action/index.js
- src/components/layout/header-actions.js
ClassName and "others" attributes were not taken in account in button rendering.
> Fixes #751
className attribute and other attributes are now rendered in action button.
> [Action button] add css className and other attributes

- src/application/popin/index.js
- src/application/popin/style/popin.scss
Correct popin close button position.
Complete last fix commit about issue #711.
Fixes #711.
> fix popin close button position. fixes #711

- src/common/mixin/store-change-behaviour.js
> [form] Fix onStatus method

- src/search/search-bar/index.js
> [search] Fix placeholder

- package.json
> feature-0.7.10-rc1

- package.json
Missed `material-ui` dependency...
> [version] 0.8.1-rc1

- src/page/search/search-header/mixin/index.js
- src/page/search/search-header/summary.js
fix react import in header search bar mixin
> fix react import in header search bar mixin

- package.json
> upgrade version 0.8.3-beta1

- src/behaviours/scroll/index.js
- src/components/scrollspy-container/index.js
Highlight an item on click
https://github.com/KleeGroup/focus-components/issues/802
> Fix sticky menu click

- package.json
Update to the new minor version of React, please read the associated [Release note](https://facebook.github.io/react/blog/2015/12/29/react-v0.14.4.html)
> feature-react-0.14.4

- .babelrc
- package.json
- src/behaviours/material/index.js
- src/behaviours/store/connect.js
- src/components/icon-dropdown/index.js
- src/components/input/autocomplete-select/__tests__/index.js
- src/components/input/autocomplete-select/consult.js
- src/components/input/autocomplete-select/edit.js
- src/components/input/autocomplete-select/field.js
- src/components/input/checkbox/index.js
- src/components/input/date/__tests__/index.js
- src/components/input/date/index.js
- src/components/input/select/index.js
- src/components/input/text/index.js
- src/components/input/textarea/index.js
- src/components/input/toggle/index.js
- src/components/layout/header-actions.js
- src/components/layout/header-content.js
- src/components/layout/header-scrolling.js
- src/components/layout/header-top-row.js
- src/components/menu/index.js
- src/components/scrollspy-container/index.js
- test/mocha-bootload.js
- test/mocha.opts
> Putting semicolons for class properties seems normal to me !
@Tommass, 01/08/2015 18h01
:smile:
> Update babel to v6

- package.json
- src/components/input/autocomplete-select/edit.js
- src/components/input/date/index.js
Fix issues induced by `startsWith` used on strings.
> Fix IE related issues

- src/application/confirmation-popin/index.js
- src/application/popin/index.js
Call the cancelHandler on popin close
> Confirmation popin fix

- package.json
- src/style/_mdl_variables.scss
Material design lite library version is upgraded to 1.0.6.
Please upgrade the library version in your project.
> [Material Design Lite] upgrade library version to 1.0.6

- package.json
Library material design icons is upgraded to latest version.
> [Material Design Icons] library upgraded

- package.json
- src/components/layout/header-scrolling.js
- src/components/layout/index.js
- src/dev-tools/loading-status-bar/index.js
- src/dev-tools/loading-status-bar/loading-status.js
- src/dev-tools/loading-status-bar/style.sass
Add a loading bar at the bottom right of the application as in Inbox app
> Feature loading status bar

- package.json
- src/components/layout/index.js
- src/dev-tools/loading-status-bar/index.js
- src/page/mixin/cartridge-behaviour.js
> Fix status bar

- src/common/mixin/store-change-behaviour.js
- src/components/layout/header-scrolling.js
> Header edit fix

- src/page/mixin/cartridge-behaviour.js
header dispatch is now done in focus-core.
> [cartridge-behaviour] fix dispatch

- src/behaviours/scroll/index.js
> Fix issue #920

- src/components/scrollspy-container/index.js
Removing 2 lines of "console.log"
> Delog unseless infos.

- src/list/summary/index.js
- src/page/search/search-header/mixin/index.js
- src/search/search-bar/index.js
An event handler called ```onScopeSelection``` is added, allowing to define precisely a custom event triggered when user click on scope and select one.
> [Seach-header] fix page search-header event handling on scope click

- src/list/selection/list.js
- src/list/selection/style/list.scss
Selection checkbox was stuck on the left side of the line. 
Selection checkbox is now place 20px from the left side.
> [Seletion-list] fix selection list default styles

- src/list/selection/list.js
> [Selection list] add deprecation

- src/components/input/checkbox/index.js
- src/components/input/checkbox/style/checkbox.scss
- src/style/index.js
> Adding error managing to input-checkbox

- .editorconfig
- package.json
Add a `.editorconfig` in the project
If you're using Atom, you must install [a plugin](https://atom.io/packages/editorconfig) to make it work.
> Feature editor config

- src/components/icon-dropdown/index.js
Translation is added on the label
Translation is added on the label, and i18n mixin is added to the component
Fixes #980
> [Issue Fixed : [icon-dropdown] Secondary buttons label are not translated] Add translation #981

- package.json
- scripts/babelify.js
Documentation on babel doc
https://babeljs.algolia.com/docs/advanced/caveats/#internet-explorer
Issue on babel 
https://phabricator.babeljs.io/T3041
> [babel] Add fixes for class in IE.

- src/search/facet-box/package.json
> [facet-box] Fix typo

- src/list/action-bar/index.js
- src/list/selection/style/list.scss
- src/page/search/advanced-search/action-bar.js
- src/page/search/advanced-search/index.js
- src/page/search/common/component/results.js
Vertigo API has changed in version 0.9.1.
FOCUS took these changes into account, following this new API: https://github.com/KleeGroup/focus-core/wiki/Search-example
> [search api] fix search api parsing

- src/components/role/__tests__/.eslintrc
- src/components/role/__tests__/index.js
- src/components/role/index.js
The compoent has been migrated in components
Test cases have been created
```jsx
// Sample code
//check one role
<Role  hasOne={['DEFAULT_ROLE']}} >
{children}
</Role>
//check many roles all are needed
<Role  hasAll={['DEFAULT_ROLE', 'ADMIN_ROLE', 'OTHER_ROLE']} >
{children}
</Role>
//optional child element when roles are not sufficient
<Role  hasOne={['DEFAULT_ROLE']}}  emptyBlock={<div>Insufficient rights</div>}>
{children}
</Role>
```
> migration component role

- src/page/search/quick-search/index.js
Missing props store passed to Results component
> [Quick-search] fix missing store props

- src/components/layout/style/header-top-row.scss
> fix input label position in search bar in cartridge

- package.json
- src/style/_mdl_variables.scss
Inline images
**You can now remove the images you were serving statically**
> Feature inline images

- src/components/menu/example/index.jsx
Minor update in the example page. Showing different informations
> Adjusting page description on the example

- src/application/popin/example/index.jsx
Updating the popin component's example page
> Updating popin example page

- src/application/popin/example/index.jsx
- src/search/facet-box/example/index.jsx
Minor changes on the popin example and minor update on the facet-box example by opening one facet.
> Updating facet box example by opening one facet

- src/list/table/README.md
LineComponent edit in readme
You must put an UpperCase to LineComponent.
LineComponent
LineComponent
> props modification

- src/application/popin/example/index.jsx
- src/page/search/quick-search/package.json
- src/search/search-bar/example/index.jsx
> Update quick search example

- README.md
> Add metrics

- package.json
- src/style/_mdl_variables.scss
Upgrade MDL library to the latest one : 1.1.2.
> [MDL] Upgrade to latest version 1.1.2

- src/common/field/__tests__/.eslintrc
- src/common/field/__tests__/index.js
- src/common/field/__tests__/test-focus.jsx
- src/components/icon-dropdown/__tests__/index.js
- src/components/icon-dropdown/index.js
- test/mocha-bootload.js
- test/test-focus.jsx
tests created for the component  Field
tests based on data-focus attribute and id
> Feature tests field

- package.json
> Remove material-design-icons

- src/components/input/text/index.js
- src/page/search/advanced-search/facet-box.js
- src/search/search-bar/index.js
All criteria were not changed on scope change.
All criteria are now changed on scope change.
> Fixes #1065
> Reset search on scope change

- package.json
> Fix env variable setting for windows

- README.md
> Add browserstack logo.

- src/components/input/autocomplete-text/edit.js
> Giving example in the edit autocomplete text and explaining the props

- package.json
- src/page/search/common/component/group-wrapper.js
- src/page/search/common/component/results.js
- src/page/search/quick-search/index.js
- src/search/search-bar/scope.js
Fixing the fact that the action was not given to the Results child.
> Fix quicksearch

- src/components/message-center/index.js
> [snackbar] Add translation

- src/common/empty/index.js
- src/components/empty/index.js
- src/components/index.js
Moving the component to the 'components' folder and rewriting its code
> Migrate 'Empty'

- src/components/empty/index.js
Fixing a mixing in the code. Check image below
> Fixng Empty Component

- src/list/table/list.js
Add a key to the table header to avoid React warning.
> [table] Add key to the table header.

- src/common/i18n/mixin/index.js
FIx `window.i18n` use which was an ugly thing.
> [i18n] fix ugly

- src/components/button-back-to-top/__tests__/index.js
- src/components/button-back/__tests__/index.js
- src/components/button/__tests__/index.js
- src/components/button/index.js
- src/components/column/__tests__/index.js
- src/components/display/checkbox/index.js
- src/components/display/text/index.js
- src/components/grid/__tests__/index.js
- src/components/icon/__tests__/index.js
- src/components/input/radio/__tests__/index.js
- src/components/input/radio/index.js
- src/components/input/select-checkbox/__tests__/index.js
- src/components/input/select-checkbox/example/index.jsx
- src/components/input/select-radio/__tests__/index.js
- src/components/input/select-radio/example/index.jsx
Testing the migrated components
> Unit tests

- src/components/button/index.js
- src/components/layout/example/index.jsx
- src/components/layout/header-actions.js
Button's alt attribute wasn't updating when a new button action was added
It was caused aused by the .map index given in the key attribute. React did have a problem to update this.
Giving the label fixes the update.
> Fixes #1088
> Fix layout bug

- src/components/input/radio/index.js
- src/components/input/select-checkbox/index.js
- src/components/input/select-radio/index.js
Adding translation on label for each component
> Updating Some Components

- src/page/search/advanced-search/index.js
- src/page/search/common/component/results.js
- src/page/search/quick-search/index.js
Fix issue https://github.com/KleeGroup/focus-components/issues/1124
Add scopesConfig prop to results component in order to resolve selected scope code.
> Fix 1124 show all not working properly

- src/common/field/mixin/built-in-components.js
Fix bug using deprecatedAutocomplete with form
> Fix bug using deprecatedAutocomplete with form

- src/common/field/mixin/built-in-components.js
> Fix bad Autocomplete component import

- src/search/search-bar/index.js
Fix issue : https://github.com/KleeGroup/focus-components/issues/1137
> hide placeholder if query is not empty

- src/common/autocomplete/awesomplete.js
- src/common/autocomplete/field.js
Alllow InputText in the props of the deprecatedAutoComplete cc @pierbrisson
> Add InputText in props

- src/components/input/autocomplete-select/example/index.jsx
- src/components/input/autocomplete-select/field.js
fix issue #1106 
Translate autocomplete badInput error message
> Fix 1106 translate autocomplete error message

- src/components/input/date/index.js
> [IE10][date picker] fix IE10  Close Date Picker by a click on the page

- src/components/button/index.js
Refactoring the code and fixing the fact that the onClick event didn't give the right arguments
> [button] Fix the onClick behaviour

- src/common/field/mixin/built-in-components.js
- src/common/form/example/index.jsx
- src/components/input/autocomplete-select/edit.js
- src/components/input/autocomplete-text/__tests__/autocomplete-text-tests.js
- src/components/input/autocomplete-text/edit.js
The autocomplete now shows the error message on the form when it's required and has no value. It now displays the error message.
> Fixes #1157
> [autocompleteText/autocompleteSelect] Fixing the error problem

- src/common/form/example/index.jsx
- src/components/input/autocomplete-select/edit.js
- src/components/input/autocomplete-text/edit.js
- src/components/input/text/index.js
Adding the i18n translation to the error display. 
Adding i18n translation on the placeholder for the autocompleteText
> [autocomplete-select/autocomplete-text/input-text] Adding Translation

- src/components/input/autocomplete-text/__tests__/autocomplete-text-tests.js
- src/components/input/autocomplete-text/edit.js
- src/components/input/autocomplete-text/example/index.jsx
> [autocomplete-text] Update the component

- src/components/input/autocomplete-text/consult.js
[autocomplete-text] Update the consult mode
Updating the consult mode to render it in a good way.
> [autocomplete-text] Update the consult mode

- src/components/button/index.js
Before the button gave an array in the arguments with the "call" function. Now you a "call" function to only give the event
> [button] Give event in arguments

- src/common/field/mixin/built-in-components.js
- src/common/mixin/built-in-components.js
- src/components/button/index.js
- src/components/button/style/button.scss
- src/components/input/autocomplete-text/edit.js
Adjusting the button style to match with the projects and givng the new components on the form to don't have the warning deprecated message by default.
> [button/form] Update components

- src/components/button-back/index.js
- src/components/menu/index.js
Updating the menu and the button back to make them work in the good way with backbone and react-router
See https://github.com/KleeGroup/focus-core/pull/355
And https://github.com/KleeGroup/focus-demo-app/pull/159/files
**Be aware that you now nedd to pass the `navigate` props  to the menu to be able to navigate with routes definitions**
See https://github.com/KleeGroup/focus-demo-app/pull/159/files#diff-7aa9ab3719adde04af90e824e3f1543fL72
> [menu/button back] Update components

- src/components/display/checkbox/index.js
Fix typo in the component display/checkbox
> [display] [checkbox] erase `this` typo

- package.json
- src/common/autocomplete/awesomplete.js
- src/common/autocomplete/field.js
- src/common/field/mixin/built-in-components.js
- src/components/display/checkbox/index.js
- src/legacy/input/text/text/index.js
> [autocomplete]

- src/components/message-center/style/message-center.scss
Snackbar in front of the popin
> Fixes #1182
> [SnackBar] Snackbar in front of popin

- src/components/input/select/index.js
Correcting misprint "mubtiple" -> "multiple"
> Fix a misprint in propTypes

- package.json
- src/components/draggable-iframe/index.jsx
- src/components/draggable-iframe/style/draggable-iframe.scss
- src/components/index.js
> [draggable-iframe] Adding the draggable-iframe component

- package.json
- src/style/index.js
Adding the style file for the draggle-iframe
> [draggable-iframe] Add style

- package.json
- src/list/table/list.js
- src/list/timeline/list.js
- src/message/index.js
Fixing bad imports on list's components
> [button] Fix bad imports

- package.json
- src/components/draggable-iframe/index.jsx
> Fix on draggable iframe

- package.json
- src/components/input/date/index.js
remove `data-reactid` from input date component
> remove data-reactid from input date component

- src/components/input/autocomplete-select/edit.js
> remove reactid from autocomplete select

- package.json
- src/components/button/index.js
> add onclick props

- src/application/content-actions/index.js
> Add dropdown in primary actions

- src/components/icon-dropdown/style.scss
> Correction display

- src/components/button-back/index.js
Just like the Menu (which I already fixed a while ago), ButtonBack lost his default prop with 0.16.
So it's back!
> [ButtonBack] Give history.back back to Back

- package.json
- src/components/draggable-iframe/style/draggable-iframe.scss
> Fix default css for iframe

- src/search/search-bar/style/search-bar.scss
> [Search Header] Change display

- src/select-mdl/index.js
- src/select-mdl/index.scss
Fixing select dropdown menu display.
> [Select-MDL] Fixing the dropdown display

- package.json
Updating the package.json to upgrade in version 3.0.0 rc2
> [Version] 3.0.0 rc2

- package.json
- src/autocomplete-select/index.js
> [Autocomplete] Fix props

- package.json
- src/index.js
> [Autocomplete] Renaming correctly the call

- package.json
- src/autocomplete-select/index.js
> [Autocomplete] Bad props

- package.json
> [Version] 3.0.0-rc13

- package.json
- src/autocomplete-text/edit.js
- src/autocomplete-text/field.js
Fixing the onChange given the props
> [Autocompelte Text] Adjust onChange

- src/components/input/autocomplete-text/__tests__/autocomplete-text-tests.js
- src/components/input/autocomplete-text/edit.js
- src/components/input/autocomplete-text/example/index.jsx
- src/components/input/autocomplete-text/field.js
Adding the debounce function as it's done in the autocomplete-select
> [Autocomplete-Text] Add debounce function

- package.json
- src/common/field/mixin/validation-behaviour.js
- src/common/form/example/index.jsx
The validator in the domain should now be called.
Fixes #1238
> [Validation-Behaviour] Adding InputDate validation

- package.json
- src/page/search/advanced-search/index.js
the function callSearchOnMount from the props wasn't call in the good way. It's now fixed
> [Advanced-Search] Updating a bad call

- package.json
- src/common/select-action/example/index.jsx
- src/common/select-action/index.js
- src/components/topic-displayer/index.js
- src/list/action-bar/index.js
Fixing the dropdown menu export and upgrading the focus-components to 2.0.0-rc4
> [Dropdown Menu] Fixing dropdown

- src/page/search/advanced-search/README.md
Add an example about how to connect a parent component to the search store and update an advanced search props given the selected scope.
> Add an example about how to connect a parent component to the search store and update an advanced search props given the selected scope.

- src/page/search/advanced-search/index.js
Report modification of PR 1276 because it not rebased.
> Report non rebased PR 1276

- package.json
Restoring the version it should have here.
> [package.json] restoring package.json version to 2.0.0

- package.json
- src/common/field/index.js
- src/common/field/mixin/validation-behaviour.js
- src/common/form/example/index.jsx
- src/components/input/date/index.js
It looks like the #1290 code wasn't merged correctly. 
I've also updated the input-date code by removing useless comments. 
I think it also fixes the #1283 issue.
> [input-date] Restoring #1290 PR code and updating input date

- src/application/popin/index.js
This is the last import of lodash as global, causing it to be exported as global.
It is causing a conflict on a project for me
@Ephrame I will come to talk about it :)
> fixing import

- src/components/input/date/__tests__/index.js
Tests were broken after some changes.
> [input-date] Fixing some tests after some moment date changes

- src/components/button/index.js
- src/components/column/index.js
- src/components/grid/index.js
> Correcting rest props (should not contain classname)

- src/components/input/date/__tests__/index.js
a .only was missing on a test so it's removed to run all tests
> [tests] Removing a missing .only on the tests

- .gitignore
- src/page/search/common/component/results.js
Display the result's number beside each group/facet
> Fix the display of result's number in search

- src/search/facet-box/facet.js
The facet title wasn't displayed when we chose one. It's now fixed
> [FACETS] Restore the facet title display

- src/search/facet-box/facet.js
cherry-picking commit https://github.com/KleeGroup/focus-components/commit/83b8410604e7a489c705ad8bfaf1a6e363e95e1e from master to develop
> Restore the facet title display

- package.json
@Hartorn 
We did this change, so I add it
> change package.json add prepublish

- package.json
- src/components/button/index.js
- src/components/column/index.js
- src/components/grid/index.js
- src/components/input/autocomplete-select/edit.js
- src/components/input/autocomplete-text/edit.js
- src/components/input/date/__tests__/index.js
- src/components/input/date/index.js
- src/components/input/text/index.js
- src/list/selection/list.js
- src/page/search/advanced-search/index.js
- src/search/facet-box/facet.js
Add otherProps in DatePicker components props to be able to use more feature of react-date-picker
> Add otherProps to datePicker

- src/common/field/mixin/built-in-components.js
- src/common/mixin/field-component-behaviour.js
- src/utils/is-react-class-component.js
Adding LabelComponent, AutocompleteSelectComponent, AutocompleteTextComponent (not AutocompleteComponent since it is deprecated)
> Missing props from form to field

- src/components/input/autocomplete-select/edit.js
- src/components/input/autocomplete-text/edit.js
- src/components/input/text/index.js
- src/components/input/textarea/index.js
Fixes the fact that when the value is equal to 0
> Fixes #1326
> [Input-Text | Textarea/Autocomplete-Text | Select] Fix input value

- package.json
- src/style/_mdl_variables.scss
Fix #1367 
Updating material-design-lite to 1.3.0
Should be put in release notes, as projects have to update to material design lite 1.3.0
> Fix mdl variables

- src/components/input/date/index.js
Fix #1357 and #1325 
Still have to test in details before merging
> Fix input date issues

- src/components/input/select-radio/index.js
- src/components/input/select-radio/style/select-radio.scss
Adding error handling on select-radio
Adding style for the error
See #1366 
Credits to @EmilienSanterre
> Adding error handling on select-radio

- src/components/panel/__tests__/index.js
- src/components/panel/index.js
- src/components/scrollspy-container/index.js
> Handling conditionnal header render

- src/common/mixin/built-in-components.js
- src/components/button/__tests__/index.js
- src/components/button/index.js
- src/components/button/style/button.scss
Adding spinner when the form is saving and disabling the button
> [Button] Updating the behaviour when the button is loading

- src/common/field/index.js
- src/common/list/index.js
- src/common/mixin/built-in-components.js
- src/common/mixin/field-component-behaviour.js
- src/common/mixin/store-behaviour.js
- src/common/mixin/store-change-behaviour.js
- src/components/button/__tests__/index.js
- src/components/button/index.js
- src/components/icon/index.js
- src/components/input/checkbox/index.js
- src/components/input/checkbox/with-error.js
- src/components/input/text/index.js
- src/list/selection/index.js
- src/list/selection/line.js
- src/list/selection/list.js
- src/list/table/index.js
- src/list/table/line.js
- src/list/table/list.js
Adding default on change on fields : state of the form contains value by default
Better cancel action (taking in account modified fields, can be customised with this.buildResetState if needed, see field-component-behaviour.js)
store-behaviour : Adding option this.props.useDefaultStoreData, to get merged object from store, with definition, or from this.getDefaultStoreData
Correcting import
Correcting indentation
> Improve form

- src/behaviours/store/connect.js
Fixing an issue about updateState not using the right props.
> Using wrong props on updateState

- src/behaviours/material/index.js
- src/components/input/text/index.js
> Fixing placeholder : should be rerender (hidden) when there is a value

- src/components/input/autocomplete-select/edit.js
Adding two options : 
- one to clear the input text when selecting in the value list
- one to clear the input text, when a null value is given (clearing the field)
> Fix autocomplete

- src/page/mixin/cartridge-behaviour.js
This modification allows to change the cartridge configuration of advanced search dynamically.
The compatibility with previous version is maintained.
> [Search Header] Change cartridge conf of advanced search dynamically

- src/search/facet-box/index.js
Fix issue #1353
Initial state is wrongly set. The component doesn't work if it is rendered only once.
> [Advancedsearch][FacetBox] missing assignment in Initial state

- .gitattributes
- src/common/form/index.js
- src/common/form/mixin/reference-behaviour.js
- src/common/mixin/store-behaviour.js
- src/common/mixin/store-change-behaviour.js
- src/common/select-action/index.js
- src/components/button-back/index.js
- src/components/icon/index.js
- src/page/search/advanced-search/list-summary.js
- src/page/search/quick-search/index.js
- src/page/search/search-header/mixin/index.js
- src/search/search-bar/index.js
- src/search/search-bar/scope.js
This PR is mainly about Advanced-Search. 
Must be treated with same PR on focus-core
The main problems are listeners not properly recreated when store or store properties are changing
see https://github.com/KleeGroup/focus-core/pull/394
> Fix advanced search

- src/components/input/autocomplete-select/edit.js
> Correcting input value in case of onSelectClear

- src/components/dropdown/index.js
> Added the type='button' to the dropdown menu

- src/components/confirm/index.js
Correction issue #1434. 
@c3dr0x can you verify if the behaviour is still the one has you wanted ?
> Fix error confirm

- package.json
- src/behaviours/lazy/index.js
Component which call the load action only when the focus is on it.
> Add lazy decorator

- src/components/input/radio/index.js
> Fixing radio display in firefox

- src/components/input/autocomplete-select/consult.js
> keyresolver should not be called with undefined or null

- src/components/message-center/index.js
Fixing the render loop in the message center. I kept the animation.
> Hotfix message center

- src/components/input/autocomplete-select/edit.js
- src/components/input/autocomplete-text/edit.js
Fix autocomplete on Autocomplete.
> Fix autocomplete on Autocomplete.

- src/common/display/text/index.js
Removed focus types import and replaced the by React PropTypes.
> Clean displayTextMixin

- src/common/form/index.js
- src/common/mixin/store-behaviour.js
> Store-behaviour : Adding current state to merging

- src/components/dropdown/action-menu.js
- src/components/dropdown/index.js
> Correcting #1500 : Dropdown not working correctly

- src/common/mixin/store-behaviour.js
With this option, if you have array-value, you can give empty array as default value.
> StoreBehaviour - Add default value from domain
