application/popin/style/popin.scss

Grey overlay now covers all the window, not just the parent.

Fix popin style

---

src/common/select-action/index.js
src/list/action-contextual/index.js

- Fix default icon on dropdown to use `more_vert`
- The line primary actions are now `icon button` with type `button`
Fix #326

Hotfix 326 secondary actions

---

src/common/button/action/example/index.js
src/common/button/action/index.js

On action-button, the conxtual help label (alt + title property) is now transleted.
fix #296

[action-button] add translation in contextual help label (on mouse hover the button)

---

src/common/field/mixin/built-in-components.js
src/common/mixin/built-in-components.js

`textFor(property, {listName: 'myList'})` can now be used the same way as the display component. 
Fix #243

Hotfix text for

---

showcase/index.html
src/input/checkbox/package.json
src/input/index.js
src/input/toggle/__tests__/.eslintrc
src/input/toggle/__tests__/index.js
src/input/toggle/example/index.js
src/input/toggle/index.js
src/input/toggle/package.json

The component no longer holds a state, it is now assumed that the value is managed by the parent through the `value` and `onChange` props.
See [here](https://github.com/KleeGroup/focus-components/blob/7259d6e1c3d8e8a0168d096a9800186545c2ef1f/src/input/toggle/example/index.js)

Feature refactor input toggle

---

src/common/mixin/store-change-behaviour.js

When there is an error, the state is read from the store.
fix #303

[store-change] On error, the state is reread from the stores, 

---

src/list/action-bar/index.js

Note : in Font-awesome there were a http://fortawesome.github.io/Font-Awesome/icon/sort-alpha-desc/ and a http://fortawesome.github.io/Font-Awesome/icon/sort-alpha-asc/
In material, there is only a https://www.google.com/design/icons/#ic_sort_by_alpha

Fix action bar Material sort icon.

---

src/list/selection/list.js

In order to avoid problems on load actions in lists, a simple console error has been added to be more explicit in case of a non array value.

[list] Add error when there is a map on a non array object

---

src/common/input/text/index.js
src/common/input/textarea/index.js

When a form is displayed by default in edit mode, the fields with placeholder are now display with overprint of the placeholder.
fix #321

[input-text + input-textarea] correction of overprint on fieldfor.

---

src/common/field/index.js
src/common/field/style/field.scss
src/common/input/text/index.js

Now display the error when the field is required.
Display also the label in red.
fix #396

[field + input-text] display error when required. fix #396

---

src/common/field/mixin/built-in-components.js
src/common/form/example/index.js
src/common/select/classic/index.js
src/common/select/classic/style/select.scss

the fieldfor select now display validation errors
it is also rendered a bit more like material design lite menu.
(for your information, we are waiting for mdl to deliver dropdown component (15th of october))

[select-classic] now display error on select field when required

---

src/common/field/mixin/built-in-components.js
src/common/label/index.js

Fix #430 Now the label props overrides the name props on fields. Add a text props on Label tag to have a different content.
```jsx
this.fieldFor('propertyName', {label: 'myAwesomeLabel')
<Label name='propertyName' text='content' />
```
Maybe this will evolve in the furure version to a `<Label name='propertyN
ame'>LabelContent<Label>`

Fix label override

---

src/components/input/text/__tests__/input-text-test.js
src/components/input/text/index.js

Input
- Formatter and unformatter now have the following signature `function(value, options){  /**options = {isEdit: true/false}; and // your code*/ return value;}`, add working test for these cases.
- The disabled property is now validate
It should fix #414

[input] Improvement on formatter and disabled.

---

src/showcase/app.js
src/showcase/catalog/catalog-search.js
src/showcase/catalog/index.js
src/showcase/router.js

- Showcase now have two routes
- `query/:your component query`
- `component/:yourcomponent name`
The component detail is no longer in a popin but in a standalone page.

Feature showcase route

---

src/common/display/text/index.js
src/common/form/example/index.js

Remove translation on getValue.
it will have impacts on boolean radio select which would not be translated anymore. Please add a formatter on you domain this way : 
```javascrit
'DO_OUI_NON': {
SelectComponent: FocusComponents.common.select.radio.component,
refContainer: {yesNoList: [{code: true, label: "select.yes"}, {code: false, label: "select.no"}]},
listName: 'yesNoList',
formatter: i18n.t(value)
}
```
Fix #367

Field For - display text : remove translation on get Value

---

src/components/layout/index.js

The use of a Layout component showed console warnings on the declaration of Element type props.
Description of Layout component props have been precised. Now console warning are no longer displayed.

[Layout] correction of props warnings

---

src/components/input/date/__tests__/index.js
src/components/input/date/index.js
test/mocha-bootload.js

`onChange` prop was not called when the users chose a date from the picker. It was only called when the input field was blurred.
Add a call to the prop in case the date is chosen from the picker

Fix #551 datapicker on change

---

src/list/action-bar/index.js
src/page/search/advanced-search/action-bar.js
src/page/search/advanced-search/index.js

The selection icon is still present even if the `isSelection` is set to `false`.
Do not display any selection dropdown in that case.

Fix #573 advanced search is selection

---

src/common/button/action/index.js

The classname is incomplete in case of `'mini-fab'`.
Add the correct classes

Fix #562 button mini fab

---

src/common/input/date/style/date.scss

The calendar is not shown when the calendar icon is clicked.
Add the click on the icon, equivalent to the focus in the field.

Fix #590 date icon clik

---

src/page/search/quick-search/index.js
src/search/search-bar/index.js

The placeholder is not translated. Moreover, the `Quicksearch` does not have the `placeholder` prop exposed.
Translate the component.
Added two props to the `QuickSearch` :
- `placeholder`
- `SearchBar`, so that you can provide any component you want for the search bar. @JoanaDalmeida

Fix #448 search bar translation

---

src/page/search/common/component/results.js

In case custom props are given to the `results` component, they are not transfered to the list.
Give the other props to the list component.

Fix #480 search results props

---

src/components/panel/style/panel.scss

These elements are cut.
Inherit from parent overflow, so that these elements are displayed.

Fix #533 panel overlay

---

src/components/input/date/index.js

When calling the `getValue`, there should be a way to transform the value before it is sent to the server.
The `InputDate` component now exposes a `beforeValueGetter` prop, which will be used when the `getValue` is called, taking the value as a parameter and returning whatever the user wants to send to the server.

Fix #599 date custom getter

---

package.json
src/components/index.js

Header default components are now published in Focus-Components

[layout] publish layout header components

---

src/application/popin/index.js

When changing the route without closing the window, the application scrollbar is not restored.
The application scrollbar is now restored when the popin is opened and unmounted.

Fix #612 Popin should restore scrollbar

---

src/components/input/date/__tests__/index.js
src/components/input/date/index.js

On a click in the picker zone, the `onChange` prop was not called with the correct date.
This was due to the `onBlur` in the input field, which was catching the event before the date picker.
This listener has been removed, and called on a click outside the date zone.

Fix bad behaviour of date picker click

---

src/page/search/common/component/group-wrapper.js
src/page/search/common/component/results.js

It was not possible to set an initial rows count in the groups of the advanced search component.
Add the `initialRowsCount` prop.

Fix #497 No configuration for initial rows count

---

src/page/search/search-header/mixin/index.js

Some of the search bar props are not exposed by the search header.
More props have been added.

Fix #633 Search header should expose more props

---

package.json
src/components/scrollspy-container/index.js

When looking for `Panels` to build the sticky menu, the `scrollSpyContainer` goes too deep in the DOM and sees the `Popins`. It souldn't explore there content.
When building the menu, the `scrollSpyContainer` now checks whether there is a `Popin` component between itself and the target `Panel`.

Fix #548 Scroll spy sees popin contents

---

src/page/search/advanced-search/index.js
src/page/search/common/component/results.js

It is now possible to get the selected items in the advanced search component.
```javascript
// Assuming this is the component containing the advanced search, with a ref associated
const selectedItems = this.refs.advancedSearch.getSelectedItems(); // this will return an array containing the selected items
```

[advanced-search] Add a getSelectedItems method

---

src/application/layout/index.js
src/application/loading-bar/index.js

When building a production version of an app, the dev bar should be hidden.
The `Layout` component now has a `displayDevBar` prop, by default set to `true`.
To hide the dev bar, simply set it to `false`.
```javascript
<Layout
// ...
displayDevBar={false}
// ...
```
Fixes #553

Fix #553 dev bar should have a prod mode

---

src/common/field/style/field.scss

Default field padding was overload by material css lib.
CSS precedence of the field is increased.

[field] fix field default css precedence to correct padding

---

src/components/panel/style/panel.scss

In a panel inside a form :
The Edit button appears only when the mouse is over the panel => OK
I click the Edit button and switch to edition mode => OK
The buttons are now Save and Cancel => OK
The buttons disappears when the mouse it out the panel => KO
> Fixes #641 
Now display action permanently when form is edited.

[panel] display action permanently when form is edit

---

src/list/table/list.js

The attributes `data-bypass` has been added to the sort links on the table.
Fixes #663

[table] Add `data-bypass` to the sort links fixes #663

---

src/components/input/select/index.js

The condition for having the possibility not to select a value was wrong.
It is now fixed. A select can have an undefined value if the `hasUndefined` property is set to `true`, or if the `isRequired` prop is set to `true` and the select does not have a value yet (in case of data creation).
Fixes #650

Fix #650 select has undefined

---

src/page/list/index.js

Fix #667 ref to the list in a list page

---

src/application/bar/index.js
src/application/cartridge/index.js
src/application/content-actions/index.js
src/application/header/index.js
src/application/loading-bar/index.js
src/application/message-center/index.js
src/common/button/back-to-top/index.js
src/common/scrollspy/index.js
src/components/layout/header-actions.js
src/components/layout/header-content.js
src/components/layout/header-scrolling.js
src/components/layout/header-top-row.js
src/page/list/index.js

Thanks to @Jerom138 with #700 which reveals an important misspelling on `componentWillUnMount ` which should have been `componentWillUnmount `.
The lifecycle methods are described [here](https://facebook.github.io/react/docs/component-specs.html)
We check all the names :
- `componentWillUnmount ` (13 errors were `componentWillUnMount `)
- `getInitialState`
- `getDefaultProps`
- `propTypes`
- `mixins`
- `displayName`
- `componentDidMount`
- `componentWillReceiveProps`
- `componentDidUpdate`
- `shouldComponentUpdate `
It fixes #701 and close #700

[lifecycle] Fix all misspelling names

---

src/common/list/index.js

Add a ref `list` on the `MemoryListComponent` in order to allow 
```javascript
//Example
this.refs['myListForComponentPropertyName'].refs.list.getSelectedItems()
```

[memory list] Add a list ref on the component

---

package.json
src/common/autocomplete/field.js

The `getValue` method returns the label instead of the code when the field has `isEdit` set to `false`.
Check if `allowUnmatchedValue` is set to `false`, and if yes then return the code.

[autocomplete] Fix getValue in consult mode

---

src/common/input/radio/index.js

The display is broken when the value comes after the initial render.
Now adjusting the `is-checked` class in the DOM to trigger the correct MDL display.
Fixes #670

[radio] Fix material look when provided value changes

---

src/components/layout/header-scrolling.js

When body scrollHeight is a little bigger than body clientHeight, weird phenomena commonly called "Zigwigwi" appeared.
> Fixes #164
To avoid this behaviour, shrink of header is not applied conditionnally to body height and header height. calculation is the following:
```javascript
const node = ReactDom.findDOMNode(this);
const bodyNode = document.body;
const value = bodyNode.scrollHeight - node.scrollHeight - bodyNode.clientHeight;
if(value > 0) {
//shrink the header
}
```
This seems to correct the zigwigwigwi behaviour.
This was tested on the focus demo app, and this correction worked. Please make us some feed back.

[header] fix zigwigwigwi

---

src/common/autocomplete/awesomplete.js

It is not possible to unselect a value in the autocomplete component.
It is now possible.
Fixes #749

[autocomplete] Cannot unselect an autocomplete

---

src/components/layout/style/header-scrolling.scss
src/components/scrollspy-container/index.js
src/components/scrollspy-container/sticky-menu.js
src/components/scrollspy-container/style/scrollspy-container.scss
src/components/scrollspy-container/style/sticky-menu.scss

Scrollspy-content and menu were are not well displayed on mobiles.
> Fixes #712 
This patch gives a first answer to responsive problems.
> Be careful, these changes may have some impact on your project. But don't worry, it's quite easy to change it ! It is described below.
MDL grid are not used anymore, so the allocated size of scrollspy menu remains the same if the windows size change.
On mobile screens, scrollspy menu is not displayed anymore on the left but at the top of the content.
The default size of the menu is 260px. It's maybe not what your project needs.
That's why you can override this default size by addeing the following CSS code in your `scrollspy-container.scss` SASS file:
```sass
$scrollspy-container-menu-size:220px;
$media-desktop-breakpoint: 840px !default;
@media …
```

[Scrollspy] Fix scrollspy responsive issues. fixes #712.

---

src/behaviours/scroll/index.js
src/components/scrollspy-container/index.js

If header is in full size, clicking on an item in the left menu doesn't display the right bloc(the scroll is too low). 
This error doesn't exist when the header is in the "scroll state".
Click on a menu element scroll the page on the right element.
> Fixes #740

[scrollspy-menu] correction of scroll position when a menu element is clicked

---

src/behaviours/definition/__tests__/definition-behaviour-test.js
src/behaviours/definition/__tests__/entity-conf-mock.json
src/behaviours/definition/index.js

Creates a **behaviour** for the `definition` related element of a component.
- `@definition('myentity.definition')`
- A definition is related to the data model
- Each field of the domain have a definition which contains its domain and the fact that it is required ot not.
- The definitions of your application should have been set using `focus-core/definition/entity/container/setEntityConfiguration`
- * @param  {string | array} definitionPath - A string or an array of the definition path to the configuration.
-  * @param  {object} additionalDefinition - If you need to override a definition for a specific component, you can use this object.
-  * @return {function} - A function to commect a component to a definition.
```jsx
Example
// ES6
class MyComponent{
render(){
return …
```

[behaviour] Feature definition behaviour

---

src/search/search-bar/scope.js

> [Scopes] can't select an icon to display in scope selector
Active scope misses an icon, in the search bar.
As in the scopes dropdown list, the active scope now has an icon and a label.
Fixes #572

[search bar] Add icon to active scope

---

src/search/search-bar/index.js
src/search/search-bar/style/search-bar.scss

When the search action is triggered, no spinner is displayed.
Add a spinner that will appear on the action call, and disappear with the server response.
Fixes #623

[search bar] No spinner on search action

---

src/components/scrollspy-container/index.js
src/list/selection/list.js

Fix debounce ScrollspyContainer.
Wire up the onSelection prop on SelectionList.
#yolo
(Sorry for the branch name)

Small fixes on Scrollspy and SelectionList

---

src/components/icon-dropdown/index.js
src/components/icon-dropdown/style.scss
src/components/index.js
src/components/layout/header-actions.js
src/style/index.js

When using the secondary actions in the header, getting asynchronously the action list breaks the dropdown menu.
Refactored the dropdown component, using Material UI's base.
Fixes #624

Fix #624 secondary actions

---

src/search/search-bar/scope.js

Scope labels were not translated which did not allowed multi-linguism.
Scope labels are now translated.

[Search] scopes are not translated

---

src/search/search-bar/scope.js

In previous versions, scope codes were used to specify the code of scope used for research but also to declare scope icon name. But most of times, we don't want to use the same code for scope and icon. Inded, icon libraries have proper names.
```javascript
{code: 'ALL', label: 'search.scope.all'},
{code: 'MOVIE', label: 'search.scope.movie'},
{code: 'PERSON',  label: 'search.scope.person'}
```
It is now possible to specify the icon name and library by specify it on the scope, like this : 
```javascript
{code: 'ALL', icon: 'all_inclusive', label: 'search.scope.all'},
{code: 'MOVIE', icon: 'movie', library:'material', label: 'search.scope.movie'},
{code: 'PERSON', icon: 'person', label: 'search.scope.person'}
```
> Fixes #834

[Search-bar] Add possibility to specify icon and library in scope, differently than using the code

---

src/common/button/action/index.js

Following the Focus version 0.8.3 update, buttons' content is now off by several pixels (1 em = 24px)
Seems like the CSS class material-icons' width has been modified
when icon is not specified, it is not rendered in button.
Fixes #828

correct icon rendering on button when no icon is specified

---

src/common/button/action/index.js

improve PR #840.
Fixes #828 
Now <span> is not rendered when no icon is specified.

[Button] correct icon rendering on button when no icon is specified

---

src/search/facet-box/style/facet-box.scss

The `facet-box` component used obsolete `FontAwesome` icons.
It shall be replaced by `Material` icons.
I replaced `FontAwesome` icons by `Material` icons.

[FacetBox] Switch style to Material.

---

src/common/form/style/form.scss

The loading state of the block was no longer displayed due to a CSS issue.
It should fix #618 #779 #823

Change panel name in loading css

---

src/page/search/advanced-search/index.js

Advanced search was launched 3 times is some cases (when more than one criteria is changed).
This behaviour is now corrected. Advanced search is now always launched onces, even all of criterias are launched.
Associated to : https://github.com/KleeGroup/focus-core/pull/279

[Advanced-search] Search was launch 3 times

---

src/application/confirmation-popin/style/confirmation-popin.scss
src/components/layout/header-scrolling.js
src/components/layout/style/header-scrolling.scss
src/page/mixin/cartridge-behaviour.js

Hello.
As mentionned in #686, which itself referenced other issues people were having with the header and cartridge, I propose here something that would solve most people issues with it (including mine).
(Don't forget the [corresponding PR in focus-core](https://github.com/KleeGroup/focus-core/pull/267))
The end result is this:
The header doesn't use a sizeMap or similar tricks anymore, it only has a **isDeployed** state that determines if the cartridge is shown or not, and an associated **canDeploy** prop, which defaults to `true`.
As shown in the gif, the `isDeployed` state changes on its own when the header has the size of the `top-bar`. Of course, if `canDeploy`is false, the header will stay collapsed whatever happens.
The cartridgeConfiguration (and applicationStore) has been updated …

Header size management refactor.

---

src/page/search/quick-search/index.js

Quick search was launched 3 times is some cases (when more than one criteria is changed).
This behaviour is now corrected. Quick search is now always launched onces, even all of criterias are launched.
Associated to : https://github.com/KleeGroup/focus-core/pull/291

[Quick-Serch] correct event listener in quick search

---

src/common/mixin/field-grid-behaviour.js

Adding optional prop 'contentSize' : allow to have label and field on different rows
Correcting the offset class for material design (https://github.com/google/material-design-lite/tree/master/src/grid)
Also adding options to manage offset on label and content

[Field-Grid-Behaviour] Adding optional props + Correction of incorrect class

---

src/list/selection/line.js

When the list receives new props, the selection is lost even if the new props are identical from the current props.
Now when the data are identical, the list keeps its selection.

[selection-line] Fix update selection on re-rendering.

---

src/search/search-bar/style/search-bar.scss

The search-bar spinner default size is corrected to fit by default in the container.

[Search-bar] fix spinner default size

---

src/application/popin/index.js

It is not possible to scroll inside a scrollable element inside a popin.
Let the user scroll wherever he wants, and hide the document scrollbar on popin opening.

[popin] Fix scroll issues

---

src/common/input/radio/index.js
src/common/select/radio/index.js

Currently, it is impossible to display a disabled selectRadio. 
disabled property has been added
modified files:
* src/common/input/radio/index.js
* src/common/select/radio/index.js
```jsx
render() {
const valuesExample = [
{code: 'A', label: 'aaaa'},
{code: 'B', label: 'bbbbb'},
{code: 'C', label: 'ccccc'},
{code: 'D', label: 'DDDD'}
];
return (
<SelectRadio value='A' values={valuesExample} disabled={true}/>
);
}
```
It fixes #653

[Select-radio] add disabled mode

---

src/page/search/advanced-search/index.js

When the scope changes, the sort info has lots of chance of not being supported by the new scope.
Unless all scopes have the same fields, but it's unlikely.
so we delete the sorting info.
Clean version on @sgoretti 's #913

Remove all sort info on scope change

---

src/list/selection/list.js

When giving a custom onSelection() props to list component, the list component itself give this custom onSelection() to the line component, instead of giving its own onSelection() called _handleLineSelection() which calls onSelection() anyway.
```
_handleLineSelection() {
...
this.props.onSelection()
}
<LineComponent
onSelection = {this._handleLineSelection}
onSelection = {this.props.onSelection}
>
```
Changed props order in Line Component call. This way, Line Component receives _handleLineSelection anyway.

[selection-list] fix props in line component call.

---

src/components/layout/header-scrolling.js

And it removes the dependances to the `mode` and `route` store nodes.
Win win for everybody.

Fix weird edge cases on header-scrolling.

---

src/components/input/textarea/index.js

Attribute `max-length=-1` has the same behaviour as `max-length=0` on IE11 (and probably older versions too), so you can't enter anything by default.

Fix textarea on IE

---

src/components/input/select/index.js

The InputSelect component now takes a prop, defaulted to 'select.unSelected' (what it was before), to be able to override locally the label for the unselected key.

Add overridable unselected label in InputSelect.

---

.github/pull_request_template.md
src/common/mixin/store-change-behaviour.js

In a `Field`, when the `entityPath` is different from the `store node`, a server-sent field error is not set on the field, due to a bad `ref` search.
The correct `ref` to the field is now computed from the field name.

Fix field error setting

---

src/list/selection/style/list.scss

Due to `translateY` and SASS prefixers, the contextual actions are rendered as blurry.
Removed the `translateY`.
> Fixes #976

[selection-list] Fix transform

---

src/page/search/advanced-search/index.js

Resolve a little issue which couldn't make the showcase work.
The showcase couldn't be launched with the line we have deleted in this fix.
Webpack couldn't find the require. It was a mistake.

Fixing ./style which breaked the showcase

---

src/page/search/search-header/mixin/index.js

Even if a store is given to the summary, it uses mostly the advancedSearchStore (preventing any customisation of the store).
Replaced advancedSearchStore with 'this.props.store' where needed.

Use props store instead of advancedSearchStore

---

src/components/input/checkbox/example/index.jsx
src/components/input/checkbox/index.js
src/components/input/checkbox/style/checkbox.scss
src/components/input/checkbox/with-error.js
src/components/input/index.js

Last commit on checkbox add a new feature : the possibility to define an error.
This new feature added  some problems too with checkbox used in List to select data : the rendering was not good.
As a checkbox handle a boolean value, his behaviour should be pure. Used in a form, it should never raised a error due to his value.
But some projects need a checkbox on which it is necessary to associate an error, to validate Terms for example : 
So, we decided to separate the checkbox used in a form with the one that displays an error.
It also correct the rendering of checkbox displayed in Lists to select a row. It is now correctly aligned in the middle of the line.

[Checkbox] Improve checkbox rendering

---

src/components/layout/index.js

Set ErrorCenter property to `null` to disable ErrorCenter component.
```jsx
const ErrorCenter = () => (null);
render(Layout, 'div#spabody', {
props: {MenuLeft: MenuLeft, ErrorCenter: ErrorCenter}
});
```

Add possibility to set ErrorCenter property as `null` to disable it.

---

src/components/layout/style/header-scrolling.scss

In the scrolling header, a z-index is set.
Remove it.
> Fixes #906

Remove z-index in scrolling header

---

src/page/search/advanced-search/group.js
src/page/search/advanced-search/index.js
src/page/search/advanced-search/style/advanced-search.scss
src/page/search/common/component/results.js

Focus did not provide a default group component in advanced search.
Now it does ! You don't have to code one yourself.

[Advanced search] add default group component

---

src/components/index.js

Role component was not declared in index.js
Component role added in index.js
```jsx
import role from './role';
export default {
.......
Role: role,
}
```

add role declaration in index.js

---

src/common/select-action/example/index.html

Select action handles now only 1 level of actions
```jsx
React.render(
React.createElement(React.createClass(FocusComponents.common.selectAction.mixin),
{operationList:[
{label: "Action_a",action: function() {alert("Action a");},style: "class"},
{label: "Action_b",action: function() {alert("Action b");}},
{label: "Action_c",action: function() {alert("Action c");}},
{label: "Action_d",action: function() {alert("Action d");}},
{label: "Action_e",action: function() {alert("Action e");}}
]}
),
document.querySelector("#select-action-container")
);
```

fix sample with one level of actions

---

src/components/layout/header-scrolling.js

[Description of the issue fixed or the new feature]
The condition wasn't properly computed for a content.clientHeight equals to 60 which result in this case to a deployThresold = 0. In this precise case, we would have to scroll to a negative top position to have the cartridge opened. We just change the condition from 'strict' to 'strict or equal' to deploy the cartridge in that case.
> Fixes #1060

FIX 1060: Cartridge in summary mode when scrolled to the top

---

src/list/selection/style/list.scss

Secondary actions are displayed under the next line.
As @gideruette suggested, add a `z-index` to the actions
> Fixes #1006

Fix list actions z-index

---

src/components/input/text/index.js

is-invalid class is not removed when field is valid again.
This is because of MDL, keeping the class in the DOM.
Force the class removal in the DOM.
> Fixes #908

is-invalid class is not removed when field is valid again

---

src/components/input/checkbox/index.js

Add the `disabled` props to the component. It was missing :-1: 
> Fixes #772 
```jsx
<Checkbox disabled={true} {...otherprops} />
<Checkbox disabled={false} {...otherprops} />
```

Add disable props to checkbox. It fixes #772.

---

package.json
scripts/babelify.js
src/behaviours/material/__tests__/index.js
src/page/search/common/component/results.js
src/search/search-bar/__tests__/search-bar-test.js
test/mocha-bootload.js

When only one group is returned, the search crashes.
Add some defensive code against this crash.
> Fixes #1056 
See [the original pull request](https://github.com/KleeGroup/focus-components/pull/1057) for more details.
@JabX

Hotfix search groups

---

src/page/search/common/component/results.js

See #862, @mouffakb explained it very well.
Add a `key` to each group, so that React unmounts and mounts new group elements. Their state is initialized correctly this way.
> Fixes #862

Fix group counts when grouping changes

---

src/list/selection/list.js

When the componenent receive a nes set of data. The `Map` of `selectedItems` do not behave as intended as it works on object instance for its key.
We now use the `JSON.stringify` object as key in order to be sure to work on data.
> Fixes #820

[selection list] The Map key is now a `stringified` #820

---

src/list/action-bar/index.js
src/list/selection/line.js
src/list/selection/list.js
src/page/search/advanced-search/index.js
src/page/search/common/component/group-wrapper.js

See @mouffakb description in #861.
Selection status is now correctly synced with the lines.
It is a button, directly clickable, not a dropdown anymore.
> Fixes #861

Fix #861 search select marker

---

src/components/input/autocomplete-select/edit.js

The `onChange` callback is triggered too early, so the `getValue` method does not provide the correct value.
The `onChange` callback is now fired after the internal state is correctly set.
> Fixes #1077

Autocomplete-select onChange is called too early

---

src/page/search/common/component/default-empty-component.js
src/page/search/common/component/results.js

[Description of the issue fixed or the new feature]
rewriting the component as a function and fixing the translation "search.empty" problem

Fix default empty translation

---

src/list/action-contextual/index.js

Advanced Search > config > lineOperationList
```javascript
lineOperationList:
[{
priority: 1,
icon: 'mail',
style: {}, <= Not required after patch
label: 'Contacter par e-mail',
action: this.emailAction
}
]
```

[Advanced Search] Fix when operation.style is undefined in lineOperationList

---

package.json

Update Material Design Lite version to 1.1.3, which is available and fix some issue about snackbar display.
Further information about this release here : https://github.com/google/material-design-lite/releases/tag/v1.1.3

upgrade mdl version to 1.1.3 & release beta version of focus

---

src/list/action-bar/index.js

> Fixes #1131 
There, i hide the checkbox when it's not need, when the isSelection is set to false
This is interesting, for example, an order button as in the issue. But if you don't have anything, you'll have this : 
So we gotta think about the logic. What do we want to display when there is no other button in the action bar

[action-bar/advanced-search] Behaviour update

---

src/search/facet-box/style/facet-box.scss

Fix facet-box title default style

[facet-box] Fix facet-box title default style

---

src/page/search/common/component/results.js

This PR fix the bug which occurs if the server response contains only one group with results.
Related issue : https://github.com/KleeGroup/focus-components/issues/867
It fixes #867

Fix bug search when server response contains only one group with results

---

src/behaviours/store/connect.js

This PR is correcting the connect.js, so it avoids setState when the component is not mounted
(Same as the othet PR, but without the other commit)

StoreBehaviour

---

package.json
src/components/menu/index.js
src/message/index.js

The `MenuItems` component is now a prop that has a default.
The `navigate` prop now defaults on `focus-core/history`.

Adds props to Menu

---

src/components/input/autocomplete-select/consult.js

The import was missing and composant couldn't be render

[Autocomplete-select] Import React is missing

---

src/common/select/radio/index.js
src/common/select/radio/style/select-radio.scss

The component doesn't show validation error. Now, it does (I think)

Add error when it is used in fieldFor

---

src/search/facet-box/facet.js

The search parsing was incorrect, it didn't preserve the sort from the server as the facet content was an object instead of an array.
It partially fixes https://github.com/KleeGroup/focus-components/issues/1207
it is also correlated to https://github.com/KleeGroup/focus-core/pull/368

Fix facet sorting

---

src/components/input/date/__tests__/index.js
src/components/input/date/index.js

Previously, it was not possible to disable input date component because otherProps were not passed to InputComponents.
Other props declared into the input date are now passed to his sub-component InputText.
```javascript
{this.fieldFor('birthDate', {options:{disabled: true}})}
```
Fixes #1212

[Input date] add otherProps into date components

---

src/components/scrollspy-container/index.js

remove react id froms scrollspy container

---

src/list/summary/index.js

Currently, when the querry is empty the sentence writes 'results for' but the flollowing is empty. So the sentence must write only 'results'

Correction for the sentence when the querry is empty

---

package.json
src/components/button-help/index.js
src/components/draggable-iframe/index.js
src/components/index.js
src/components/panel/index.js
src/components/panel/style/panel.scss

It is an icon button that opens the help center with the current URL and the block given as prop. It is integrated into the `Panel` component through a new `showHelp` prop that generates the blockName from the `title` and the `spyId`.
Currently, the spyId on each Panel is given by the `uniqueId` method from lodash, which gives a new number for each new Panel that is instantiated in the app. So that means that the spyIds aren't constant, so they can't be used as an id for identifying a block. To remedy this, I redefine the spyId for each Panel on its `componentDidMount()`event so that it matches its position in the Scrollspy if it is indeed in one. Otherwise, it's set to 0. I'm pretty sure it won't break anything since those spyIds weren't reliable. 
The component now handles its own …

Add ButtonHelp and add toggle logic to DraggableIframe

---

package.json
src/components/panel/index.js

Misspelled a PropType ( :trollface: ) and reduced the help block name to the first word of the title instead of everything (I had a problem with a title like `Contacts (2)` where the number could obviously change).
Also adds a `blockName` prop to override the generated blockName (that doesn't include any spyId anymore)

Panel fixes for help center

---

src/page/search/advanced-search/index.js

The action's call during the will mount is now an option. This modifcation fix an issue when only one scope is selected.
Currently, the component does two call when we dispatch a scope. An unscoped call and a call with the good scope. 
Now, when the option is false the first isn't done.

change on advancedSearch - willMount action's call in option

---

package.json
src/components/button-back-to-top/index.js

Switching from `type='submit'` to `type='button'` by default

[Button Back To Top] Button Type

---

package.json
src/common/field/index.js
src/common/field/mixin/validation-behaviour.js
src/common/form/example/index.jsx
src/components/input/date/__tests__/index.js
src/components/input/date/index.js

The validator in the domain for a inputDate was never called.
https://github.com/KleeGroup/focus-components/blob/43ed4a403b525c5847dd923f9c3055db66a24d8f/src/common/field/mixin/validation-behaviour.js#L60
The function validate in the inputDate is always called instead of the validator in the domain.
It now : 
[*] call the date validator
[*] call the date validator
[Description of the fix]
> Fixes #1238

[Input Date/Field Component] Fixing validate call 

---

src/components/button/example/index.jsx
src/components/button/index.js
src/components/menu/example/index.jsx
src/components/menu/index.js

Previously the given props didn't take the whole dom props' possibilities. 
Now it's more efficient and it can take props as onMouseEnter respecting the React 15 domain props. It prevents warning
If a project give a prop to a button and the prop isn't recognized by React as a legal DOM attribute/property React will throw a warning.
Please read the https://facebook.github.io/react/warnings/unknown-prop.html documentation.
> Fixes #1294

[Button/Menu] Adjusting button props

---

src/components/display/text/index.js

Removing translate, since it is breaking input in consult mode.
@GuenoleK Why put it ? Mistake ?

Removing translate in displayText

---

src/common/mixin/store-change-behaviour.js

If the status is set in the state after the errors are set, it triggers a new render, so the errors are not displayed anymore.
It should be done after.
@GuenoleK  @TomGallon Any case it should not be the case ?

Fixing store-change-behaviour

---

src/components/input/date/index.js

Some modification on input-date : 
- using moment.utc instead of moment
- removing call to moment.locale
- correcting the date if necessary, by adding tht utcOffset of the concerned date : `moment.utc(date).add(moment(date).utcOffset(), 'minutes').toISOString();`

Using UTC in input, removing call to moment.locale

---

src/list/selection/list.js
src/page/search/advanced-search/index.js

We render the list when the selected list it newly empty
> Fixes #1318

[SelectionList] Fixing the fact the result list wasnt refreshed

---

src/components/input/autocomplete-select/edit.js
src/components/input/autocomplete-text/edit.js
src/components/input/text/index.js

This PR fixes the fact warnings from React 15 were sent because of unknow HTML attributes.
It's now managed on InputText, AutocompletSelect and AutocompleteText as it was done on 2.1.1 for the Button component.

Update inputs props

---

src/components/icon-dropdown/index.js

VISION needs a dropdown that does not propagate an event. I have added the possibility to give the button type to the dropdown component. I have kept a default prop for the button at "submit", so that it will not affect existing dropdowns.
[Description of the issue fixed or the new feature]
[Screenshots if possible in case of a new feature]
[Description of the fix]
> Fixes #ISSUE(S)_NUMBER
```jsx
// Sample code
```

Add possibility to give the button type

---

src/common/form/mixin/validation-behaviour.js
src/utils/is-react-class-component.js

Rewrite validation
Clean up deprecated code
It is a pain to use custom component with validation inside a form :
if the component extends validationBehvaiour, this._validate or validate return a boolean value, like true, and not undefined.
So, if a form is calling it, the form will be invalid

Clean up and fix validation behaviour

---

src/search/facet-box/facet.js

Happened when : facet is selected, a search is performed but this facet no longer exists or is empty.
is-react-class-component.js:66 Uncaught TypeError: Cannot read property 'label' of undefined
at Object._renderFacetTitle (is-react-class-component.js:66)

 Advanced Search : facet label undefined fix

---

src/behaviours/scroll/index.js

When the domNode is null domNode.getBoundingClientRect() can't be executed. I think the bahaviour should be the same, if domNode is undefiend or null.

Correction when domNode is null

---

src/common/field/mixin/built-in-components.js

Fix dans la cas où on utilise InputLabelComponent de built-in-components.
```jsx
foofield: {
domain: "DO_BAR",
InputLabelComponent: Baz
}
```

[built-in-components] fix InputLabelComponen

---

src/common/mixin/field-component-behaviour.js

Wrapped onChange must always be called, and not overriden by options or def

Fixing _modifiedFields by forcing wrappedOnChange

---

src/components/tooltip/index.js

Fix issue #1399
Generated classname concat both custom and own classes without space between em

Tooltip doesn't take className well

---

src/components/input/autocomplete-select/edit.js

Fix issue #1405
If inputValue is set to null it is not passed to the input. It must be set to an empty string in order to work properly.

[Autocomplete] Label not cleared after setting value to null

---

src/common/mixin/store-behaviour.js
src/common/mixin/store-change-behaviour.js

Fix issue #1404 
If a store is udpated then the store-behavior execute the `getStateFromStore` and updates all listened nodes in state.
When the `onChange` callback is called, a list of nodes' name is passed down to the `getStateFromStore` to pick only the updated node.

[StoreChangeBehavior] Store change should only update the modified node

---

src/components/input/select-checkbox/index.js

Fix issue #1412 
`onChange` is called with two parameters : `key` and `newStatus`
- `onChange` is now called by default with the newly selected values as an array of key
- A new option `legacyOnChange` is available to get the old behavior
The `field-component-behaviour._wrappedOnChange` method will truncate the second parameter. Therefore legacy `onChange `will not work when inside a `fieldFor`

[SelectCheckbox] fix onChange behavior

---

src/common/mixin/store-behaviour.js
src/common/mixin/store-change-behaviour.js

Fix issue #1411 
`StoreChangeBehavior::storeChange` call a `onChange` method giving it the `changeInfos`.
If a component is used within a `fieldFor` then a generic `onChange` is given. 
1. The method used by StoreChangeBehavior will be renamed to `storeOnChange` to ensure no collision with forms' `onChange` methods.
2. There is a typo with `getDefaultStoreData`
Add a hook on `onStoreError` to retrieve more easily error on nodes

[StoreChangeBehavior] Fix storeChange should not trigger onChange

---

src/application/popin/index.js

The header is not fixed if opening and closing a popin
When scrolling, the header disappear
I think visible is the default value for overflow, not auto.

Fixing issue with header

---

src/components/input/date/index.js

Doing this cut in half the size of react-date-picker dependency

Input Date - Target more precisely the MonthView

---

package.json
src/components/input/date/index.js

The new version has a different visual.
Reverting to avoid visual regression

InputDate - Reverting react-date-picker to 3.1.10

---

src/common/form/mixin/reference-behaviour.js
src/common/mixin/store-behaviour.js
src/common/mixin/store-change-behaviour.js

The new feature to push into store only the updated node removes an edge cases that is exploited.
It should be deactivated by default to avoid breaking changes.
Add a call to `_getStateFromStores` within mixin willMount

[StoreChangeBehavior] add initial call to `_getStateFromStores` in will mount

---

src/behaviours/store/connect.js

With the new export, if we call a storeBuilder() in an export, the result will be done before the lunching of the application. 
So, with this modification, we could give a function. The function will be call at the onMount of the connect.

[Connect] Add possibility to give a function for store

---

src/components/message-center/index.js

To avoid the message center to stay at the bottom of the page when there is no more messages and when the last message was in multiple lines, clear the last message when the closing animation has ended.

Clear message center if there is no more message

---

src/common/form/mixin/validation-behaviour.js

named export isn't necessary here, we're exporting a mixin

[FormMixin] Validation - unnecessary named export

---

src/common/form/mixin/reference-behaviour.js

In some case, it causes infinite re-render

Reference-behaviour : avoid reloading reference list if not needed

---

src/components/input/autocomplete-text/field.js

The _handleAutocompleteChange method is not given as a props to the Edit component. 
I didn't see any use of the onChange props in the Edit component ( it is overloaded by onQueryChange, which also does not use onChange props ), so i think the method can be removed.

_handleAutocompleteChange as props to Edit component

---

src/common/mixin/built-in-components.js

[build-in-components]
Errors should be cleared & recalculated right before the save. This way, if the form has multiple errors, the user can correct the first error, click save & only the remaining errors will be shown.
Right now, errors are not cleared on Save. So the components still have an error props, even though they are no errors.

Form error clean-up

---

src/common/form/mixin/validation-behaviour.js

Both validations should be called at all time.

Form should call _customValidation even if fields aren't valid

---

src/application/content-actions/index.js
src/common/select-action/index.js
src/components/button/index.js
src/components/icon-dropdown/index.js
src/components/layout/header-actions.js
src/components/layout/header-content.js
src/components/layout/style/header-actions.scss
src/components/layout/style/header-scrolling.scss

Fix: #1467
* **primary**: now accepts an `iconLibrary` option to change icon library.
* **secondary**: can now be an object with keys similar to **primary**: `icon`, `iconLibrary`, `action`. 
```js
{
primary: [
{ icon, iconLibrary, label, className, action },
// or
{ icon, iconLibrary, action: [
{ label, action, style },
[...]
]},
[...]
],
secondary: [
{ label, action, style },
[...]
],
// or
secondary: { icon, iconLibrary, action: [
{ label, action, style },
[...]
]}
}
```
note: `style` prop in action array is only available in legacy component.

Add iconLibrary options to content-actions
